/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DateOnly } from './DateOnly';
import {
    DateOnlyFromJSON,
    DateOnlyFromJSONTyped,
    DateOnlyToJSON,
} from './DateOnly';
import type { FrequenceMode } from './FrequenceMode';
import {
    FrequenceModeFromJSON,
    FrequenceModeFromJSONTyped,
    FrequenceModeToJSON,
} from './FrequenceMode';

/**
 * 
 * @export
 * @interface AddRepetitiveBillingRequest
 */
export interface AddRepetitiveBillingRequest {
    /**
     * 
     * @type {string}
     * @memberof AddRepetitiveBillingRequest
     */
    portfolioId?: string | null;
    /**
     * 
     * @type {DateOnly}
     * @memberof AddRepetitiveBillingRequest
     */
    date?: DateOnly;
    /**
     * 
     * @type {string}
     * @memberof AddRepetitiveBillingRequest
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddRepetitiveBillingRequest
     */
    amount?: number;
    /**
     * 
     * @type {FrequenceMode}
     * @memberof AddRepetitiveBillingRequest
     */
    frequenceMode?: FrequenceMode;
}

/**
 * Check if a given object implements the AddRepetitiveBillingRequest interface.
 */
export function instanceOfAddRepetitiveBillingRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddRepetitiveBillingRequestFromJSON(json: any): AddRepetitiveBillingRequest {
    return AddRepetitiveBillingRequestFromJSONTyped(json, false);
}

export function AddRepetitiveBillingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRepetitiveBillingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': !exists(json, 'portfolioId') ? undefined : json['portfolioId'],
        'date': !exists(json, 'date') ? undefined : DateOnlyFromJSON(json['date']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'frequenceMode': !exists(json, 'frequenceMode') ? undefined : FrequenceModeFromJSON(json['frequenceMode']),
    };
}

export function AddRepetitiveBillingRequestToJSON(value?: AddRepetitiveBillingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'date': DateOnlyToJSON(value.date),
        'name': value.name,
        'amount': value.amount,
        'frequenceMode': FrequenceModeToJSON(value.frequenceMode),
    };
}

