/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingId
 */
export interface BillingId {
    /**
     * 
     * @type {string}
     * @memberof BillingId
     */
    readonly guid?: string;
}

/**
 * Check if a given object implements the BillingId interface.
 */
export function instanceOfBillingId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BillingIdFromJSON(json: any): BillingId {
    return BillingIdFromJSONTyped(json, false);
}

export function BillingIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guid': !exists(json, 'guid') ? undefined : json['guid'],
    };
}

export function BillingIdToJSON(value?: BillingId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

