/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteRepetitiveBillingRequest
 */
export interface DeleteRepetitiveBillingRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteRepetitiveBillingRequest
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteRepetitiveBillingRequest
     */
    repetitiveBillingId: string;
}

/**
 * Check if a given object implements the DeleteRepetitiveBillingRequest interface.
 */
export function instanceOfDeleteRepetitiveBillingRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;
    isInstance = isInstance && "repetitiveBillingId" in value;

    return isInstance;
}

export function DeleteRepetitiveBillingRequestFromJSON(json: any): DeleteRepetitiveBillingRequest {
    return DeleteRepetitiveBillingRequestFromJSONTyped(json, false);
}

export function DeleteRepetitiveBillingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRepetitiveBillingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
        'repetitiveBillingId': json['repetitiveBillingId'],
    };
}

export function DeleteRepetitiveBillingRequestToJSON(value?: DeleteRepetitiveBillingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'repetitiveBillingId': value.repetitiveBillingId,
    };
}

