/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeletePortfolioRequest
 */
export interface DeletePortfolioRequest {
    /**
     * 
     * @type {string}
     * @memberof DeletePortfolioRequest
     */
    portfolioId: string;
}

/**
 * Check if a given object implements the DeletePortfolioRequest interface.
 */
export function instanceOfDeletePortfolioRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;

    return isInstance;
}

export function DeletePortfolioRequestFromJSON(json: any): DeletePortfolioRequest {
    return DeletePortfolioRequestFromJSONTyped(json, false);
}

export function DeletePortfolioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletePortfolioRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
    };
}

export function DeletePortfolioRequestToJSON(value?: DeletePortfolioRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
    };
}

