/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBillingRequest
 */
export interface DeleteBillingRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteBillingRequest
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteBillingRequest
     */
    billingId: string;
}

/**
 * Check if a given object implements the DeleteBillingRequest interface.
 */
export function instanceOfDeleteBillingRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;
    isInstance = isInstance && "billingId" in value;

    return isInstance;
}

export function DeleteBillingRequestFromJSON(json: any): DeleteBillingRequest {
    return DeleteBillingRequestFromJSONTyped(json, false);
}

export function DeleteBillingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBillingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
        'billingId': json['billingId'],
    };
}

export function DeleteBillingRequestToJSON(value?: DeleteBillingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'billingId': value.billingId,
    };
}

