/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditPortfolioRequest
 */
export interface EditPortfolioRequest {
    /**
     * 
     * @type {string}
     * @memberof EditPortfolioRequest
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof EditPortfolioRequest
     */
    name: string;
}

/**
 * Check if a given object implements the EditPortfolioRequest interface.
 */
export function instanceOfEditPortfolioRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function EditPortfolioRequestFromJSON(json: any): EditPortfolioRequest {
    return EditPortfolioRequestFromJSONTyped(json, false);
}

export function EditPortfolioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditPortfolioRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
        'name': json['name'],
    };
}

export function EditPortfolioRequestToJSON(value?: EditPortfolioRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'name': value.name,
    };
}

