/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DateOnly } from './DateOnly';
import {
    DateOnlyFromJSON,
    DateOnlyFromJSONTyped,
    DateOnlyToJSON,
} from './DateOnly';
import type { FrequenceMode } from './FrequenceMode';
import {
    FrequenceModeFromJSON,
    FrequenceModeFromJSONTyped,
    FrequenceModeToJSON,
} from './FrequenceMode';

/**
 * 
 * @export
 * @interface EditRepetitiveBillingRequest
 */
export interface EditRepetitiveBillingRequest {
    /**
     * 
     * @type {string}
     * @memberof EditRepetitiveBillingRequest
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof EditRepetitiveBillingRequest
     */
    repetitiveBillingId: string;
    /**
     * 
     * @type {DateOnly}
     * @memberof EditRepetitiveBillingRequest
     */
    date: DateOnly;
    /**
     * 
     * @type {string}
     * @memberof EditRepetitiveBillingRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof EditRepetitiveBillingRequest
     */
    amount: number;
    /**
     * 
     * @type {FrequenceMode}
     * @memberof EditRepetitiveBillingRequest
     */
    frequenceMode: FrequenceMode;
}

/**
 * Check if a given object implements the EditRepetitiveBillingRequest interface.
 */
export function instanceOfEditRepetitiveBillingRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;
    isInstance = isInstance && "repetitiveBillingId" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "frequenceMode" in value;

    return isInstance;
}

export function EditRepetitiveBillingRequestFromJSON(json: any): EditRepetitiveBillingRequest {
    return EditRepetitiveBillingRequestFromJSONTyped(json, false);
}

export function EditRepetitiveBillingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditRepetitiveBillingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
        'repetitiveBillingId': json['repetitiveBillingId'],
        'date': DateOnlyFromJSON(json['date']),
        'name': json['name'],
        'amount': json['amount'],
        'frequenceMode': FrequenceModeFromJSON(json['frequenceMode']),
    };
}

export function EditRepetitiveBillingRequestToJSON(value?: EditRepetitiveBillingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'repetitiveBillingId': value.repetitiveBillingId,
        'date': DateOnlyToJSON(value.date),
        'name': value.name,
        'amount': value.amount,
        'frequenceMode': FrequenceModeToJSON(value.frequenceMode),
    };
}

