/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FrequenceMode = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type FrequenceMode = typeof FrequenceMode[keyof typeof FrequenceMode];


export function FrequenceModeFromJSON(json: any): FrequenceMode {
    return FrequenceModeFromJSONTyped(json, false);
}

export function FrequenceModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequenceMode {
    return json as FrequenceMode;
}

export function FrequenceModeToJSON(value?: FrequenceMode | null): any {
    return value as any;
}

