/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkAsCheckedRequest
 */
export interface MarkAsCheckedRequest {
    /**
     * 
     * @type {string}
     * @memberof MarkAsCheckedRequest
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof MarkAsCheckedRequest
     */
    billingId: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarkAsCheckedRequest
     */
    checked: boolean;
}

/**
 * Check if a given object implements the MarkAsCheckedRequest interface.
 */
export function instanceOfMarkAsCheckedRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;
    isInstance = isInstance && "billingId" in value;
    isInstance = isInstance && "checked" in value;

    return isInstance;
}

export function MarkAsCheckedRequestFromJSON(json: any): MarkAsCheckedRequest {
    return MarkAsCheckedRequestFromJSONTyped(json, false);
}

export function MarkAsCheckedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkAsCheckedRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
        'billingId': json['billingId'],
        'checked': json['checked'],
    };
}

export function MarkAsCheckedRequestToJSON(value?: MarkAsCheckedRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'billingId': value.billingId,
        'checked': value.checked,
    };
}

