/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfoliosProjectionArgs
 */
export interface PortfoliosProjectionArgs {
    /**
     * 
     * @type {string}
     * @memberof PortfoliosProjectionArgs
     */
    readonly argsType: string;
    /**
     * 
     * @type {number}
     * @memberof PortfoliosProjectionArgs
     */
    version: number;
}

/**
 * Check if a given object implements the PortfoliosProjectionArgs interface.
 */
export function instanceOfPortfoliosProjectionArgs(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "argsType" in value;
    isInstance = isInstance && "version" in value;

    return isInstance;
}

export function PortfoliosProjectionArgsFromJSON(json: any): PortfoliosProjectionArgs {
    return PortfoliosProjectionArgsFromJSONTyped(json, false);
}

export function PortfoliosProjectionArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfoliosProjectionArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'argsType': json['argsType'],
        'version': json['version'],
    };
}

export function PortfoliosProjectionArgsToJSON(value?: PortfoliosProjectionArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}

