/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioItem
 */
export interface PortfolioItem {
    /**
     * 
     * @type {string}
     * @memberof PortfolioItem
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItem
     */
    readonly name: string;
}

/**
 * Check if a given object implements the PortfolioItem interface.
 */
export function instanceOfPortfolioItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "portfolioId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function PortfolioItemFromJSON(json: any): PortfolioItem {
    return PortfolioItemFromJSONTyped(json, false);
}

export function PortfolioItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolioId'],
        'name': json['name'],
    };
}

export function PortfolioItemToJSON(value?: PortfolioItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
    };
}

