/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RepetitiveBillingItem } from './RepetitiveBillingItem';
import {
    RepetitiveBillingItemFromJSON,
    RepetitiveBillingItemFromJSONTyped,
    RepetitiveBillingItemToJSON,
} from './RepetitiveBillingItem';

/**
 * 
 * @export
 * @interface RepetitiveBillingItemArrayRequestResult
 */
export interface RepetitiveBillingItemArrayRequestResult {
    /**
     * 
     * @type {Array<RepetitiveBillingItem>}
     * @memberof RepetitiveBillingItemArrayRequestResult
     */
    result: Array<RepetitiveBillingItem>;
    /**
     * 
     * @type {number}
     * @memberof RepetitiveBillingItemArrayRequestResult
     */
    version: number;
}

/**
 * Check if a given object implements the RepetitiveBillingItemArrayRequestResult interface.
 */
export function instanceOfRepetitiveBillingItemArrayRequestResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "version" in value;

    return isInstance;
}

export function RepetitiveBillingItemArrayRequestResultFromJSON(json: any): RepetitiveBillingItemArrayRequestResult {
    return RepetitiveBillingItemArrayRequestResultFromJSONTyped(json, false);
}

export function RepetitiveBillingItemArrayRequestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepetitiveBillingItemArrayRequestResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': ((json['result'] as Array<any>).map(RepetitiveBillingItemFromJSON)),
        'version': json['version'],
    };
}

export function RepetitiveBillingItemArrayRequestResultToJSON(value?: RepetitiveBillingItemArrayRequestResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': ((value.result as Array<any>).map(RepetitiveBillingItemToJSON)),
        'version': value.version,
    };
}

