/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DateOnly } from './DateOnly';
import {
    DateOnlyFromJSON,
    DateOnlyFromJSONTyped,
    DateOnlyToJSON,
} from './DateOnly';
import type { FrequenceMode } from './FrequenceMode';
import {
    FrequenceModeFromJSON,
    FrequenceModeFromJSONTyped,
    FrequenceModeToJSON,
} from './FrequenceMode';

/**
 * 
 * @export
 * @interface RepetitiveBillingItem
 */
export interface RepetitiveBillingItem {
    /**
     * 
     * @type {string}
     * @memberof RepetitiveBillingItem
     */
    readonly repetitiveBillingId: string;
    /**
     * 
     * @type {DateOnly}
     * @memberof RepetitiveBillingItem
     */
    date: DateOnly;
    /**
     * 
     * @type {string}
     * @memberof RepetitiveBillingItem
     */
    readonly label: string;
    /**
     * 
     * @type {number}
     * @memberof RepetitiveBillingItem
     */
    readonly amount: number;
    /**
     * 
     * @type {FrequenceMode}
     * @memberof RepetitiveBillingItem
     */
    frequence: FrequenceMode;
}

/**
 * Check if a given object implements the RepetitiveBillingItem interface.
 */
export function instanceOfRepetitiveBillingItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "repetitiveBillingId" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "frequence" in value;

    return isInstance;
}

export function RepetitiveBillingItemFromJSON(json: any): RepetitiveBillingItem {
    return RepetitiveBillingItemFromJSONTyped(json, false);
}

export function RepetitiveBillingItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepetitiveBillingItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'repetitiveBillingId': json['repetitiveBillingId'],
        'date': DateOnlyFromJSON(json['date']),
        'label': json['label'],
        'amount': json['amount'],
        'frequence': FrequenceModeFromJSON(json['frequence']),
    };
}

export function RepetitiveBillingItemToJSON(value?: RepetitiveBillingItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': DateOnlyToJSON(value.date),
        'frequence': FrequenceModeToJSON(value.frequence),
    };
}

