/* tslint:disable */
/* eslint-disable */
/**
 * MyPersonalAccounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProjectionArgs,
} from '../models';
import {
    ProjectionArgsFromJSON,
    ProjectionArgsToJSON,
} from '../models';

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     */
    async apiEventsGetEventsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectionArgs>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Events/GetEvents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectionArgsFromJSON(jsonValue));
    }

    /**
     */
    async apiEventsGetEventsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectionArgs> {
        const response = await this.apiEventsGetEventsGetRaw(initOverrides);
        return await response.value();
    }

}
